import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from 'next/font/local'

import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const inter = localFont({ src: './fonts/inter/InterVariable-Italic.ttf' })

export const metadata: Metadata = {
  // title: "Create Next App",
  title: {
    template: '%s | ABC', // 模板
    default: 'Default Title', // 默认标题
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

